Collision population/tuyaux
Ajout de la collision de chaque oiseau avec les tuyaux. Pour cela, ajout d'une boucle for parcourant chaque oiseau de la liste content la population. La boucle vérifie des conditions au cas par cas et élimine des oiseaux selon le résultat des conditions.

Bug lorsque tous les oiseaux perdent, apparaît parfois (reste à savoir quand) :
 File "main.py", line 331, in <module>
    if pipes2.collide(birdsPopulation[n], window) == True:
IndexError: list index out of range